version: '3'
services:
  node-api:
    container_name: node-api
    restart: always
    build: .
    ports:
      - '5050:5050'
    links:
      - mongo
  node-client:
    container_name: node-client
    restart: always
    build:
      context: ./client
    ports:
      - '5051:5051'
    links:
      - node-api
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-data:/data/db

volumes:
  mongo-data:
