export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
export const SET_ERROR = 'SET_ERROR'
export const SET_VISITOR = 'SET_VISITOR'
export const SHOW_LOGO = 'SHOW_LOGO'
export const HIDE_LOGO = 'HIDE_LOGO'
export const ROTATE_LOGO = 'ROTATE_LOGO'
export const SHOW_MAIN_CONTENT = 'SHOW_MAIN_CONTENT'

